# Dependencies
markdown:	redcarpet
pygments:	true
relative_permalinks: false
baseurl: /blog
# Permalinks
permalink:	/:title

# Setup
title:		 Ehsan Asdar
tagline:	'blog'
description:	'My personal blog.'
url:		/blog

author:
  name:		'Ehsan Asdar'
  url:		https://google.com/+EhsanAsdar

paginate:	5
# Custom vars
icon:		/blog/assets/images/icon.png
cover:		/blog/assets/images/cover.jpg

social:
  - icon:	github
    url:	https://github.com/oksisane
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+EhsanAsdar
    desc:	Add me on google+

  - icon:	feed
    url:	/blog/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	Blog
    url:	/blog
    
copyright:
  author:	Camporez
  url:		http://camporez.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
